export enum Actions {
  FETCH_ALL_USER_JOURNALS_REQUEST = 'FETCH_ALL_USER_JOURNALS_REQUEST',
  FETCH_ALL_USER_JOURNALS_SUCCESS = 'FETCH_ALL_USER_JOURNALS_SUCCESS',
  FETCH_ALL_USER_JOURNALS_FAIL = 'FETCH_ALL_USER_JOURNAL_FAIL',
}
