export enum Actions {
  CHECK_USER_AUTH_STATUS_REQUEST = 'CHECK_USER_AUTH_STATUS_REQUEST',
  CHECK_USER_AUTH_STATUS_SUCCESS = 'CHECK_USER_AUTH_STATUS_SUCCESS',
  CHECK_USER_AUTH_STATUS_FAIL = 'CHECK_USER_AUTH_STATUS_FAIL',
}
